import Head from 'next/head'
import Image from 'next/image'
import Content from "components/blogHero/BlogHero";
import TopPost from "components/titleText/TopPost";
import Blog from "components/blogSection/BlogSection";
import Feature from "components/category/Category";
import AllPost from "components/titleText/AllPost";
import AllBlog from "components/fullBlog/AllBlog";


export default function Home() {
  return (
    <>
      <Head>
        <title>Droomium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Content/>
      <TopPost />
      <Blog />
      <Feature />
      <AllPost />
      <AllBlog />

    </>
  )
}
