import React from 'react'
import Head from 'next/head';
import CompanyHero from 'components/mainPage/company/CompanyHero';
import CompStep from 'components/mainPage/company/CompStep';
import DroomDeep from 'components/mainPage/company/DroomDeep';
import CompBlog from 'components/mainPage/company/CompBlog';
import CompHire from 'components/mainPage/company/CompHire';


if(process.env.APP_env === 'development') {
  var api_origin = 'https://api.droomwork.io'
} else {
  api_origin = 'http://api.droomwork.io'
  // api_origin = 'http://localhost:3000'
}

if (typeof window !== "undefined") {
  const urlParams = new URLSearchParams(window.location.search)
  const TokenAuthless = urlParams.get('enter')
  if(TokenAuthless){localStorage.setItem('authless', JSON.stringify(TokenAuthless))}
  var Token = JSON.parse(localStorage.getItem("authless"))
}

function company({blogData}) {
  return (
    <>
      <Head>
        <title>Droomwork</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="container mx-auto">
          <CompanyHero />
          <div className="bg-[#f7f7f7]">
            <CompStep />
            <CompHire />
            <DroomDeep />
            
          </div>
          <CompBlog shortBlog={blogData} />
          
        </div>
    </>
  )
}

export default company

export async function getStaticProps(){

  const response = await fetch(`${api_origin}/api/v1/admin/getBlogPosts`, {
    headers:{
      'Accept':'application/json',
      'User-Agent': '*',
      'Authorization': `Bearer ${Token}`,
      'Content-type':'application/json',
      'Access-Control-Allow-Origin':'*'
    }
  })
  // const data = await JSON.stringify(response.data)
  const data = await response.json()
  // const data = datat.data.data

  return{
    props:{
      blogData: data
    },
    revalidate: 10,
  }
}