import React from 'react'
import Head from 'next/head';
import CompanyForm from 'components/mainPage/companyForm/CompanyForm';

export default function StepForm() {
  return (
    <>
        <Head>
        <title>Droomwork</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <CompanyForm />
    </>
  )
}

StepForm.getLayout = function pageLayout(page) {
  return(
      <>
          {page}
      </>
  )
}