import React from 'react'
import Head from 'next/head';
import DevPage from 'components/mainPage/developersPage/DevPage';

function DevelopersPage() {
  return (
    <>
        <Head>
          <title>Droomwork</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <DevPage />
    </>
  )
}

export default DevelopersPage;