import React, {useState} from 'react';
import Head from 'next/head';
import HeroPage from 'components/mainPage/hirePage/HeroPage';
import WhySection from 'components/mainPage/hirePage/WhySection';
import TeamPage from 'components/mainPage/hirePage/TeamPage';
import CompStep from 'components/mainPage/company/CompStep';
import WhatPage from 'components/mainPage/hirePage/WhatPage';
import PricingPage from 'components/mainPage/hirePage/PricingPage';
import HireSteps from 'components/mainPage/hirePage/HireSteps';

export default function Home() {
    return(
        <>
            <Head>
                <title>Droomwork ~ Hire Best Freelancers</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HeroPage />
            <WhySection />
            <TeamPage />
            <CompStep />
            <WhatPage />
            <PricingPage />
            <HireSteps />

        </>
    )
}