import React, {useState} from 'react';
import Head from 'next/head';
import LoginForm from 'components/mainPage/loginRegister/loginForm';


export default function Login() {

    return (
    <>
        <Head>
        <title>Droomwork</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <LoginForm className="h-full m-0 grid" />


    </>
    )
}

Login.getLayout = function pageLayout(page) {
    return(
        <>
            {page}
        </>
    )
}