import React, {useState} from 'react';
import Head from 'next/head';
import RegisterForm from 'components/mainPage/loginRegister/registerForm';


export default function Register() {

    return (
    <>
        <Head>
        <title>Droomwork</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <RegisterForm className="h-full m-0 grid" />

    </>
    )
}

Register.getLayout = function pageLayout(page) {
    return(
        <>
            {page}
        </>
    )
}